language: node_js
node_js: node

env:
  - NODE_PATH=src/

install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.6.0
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn install

script:
  - yarn eslint
  - yarn test --coverage --verbose
  - yarn flow
  - yarn build

deploy:
  provider: npm
  email: zouxuoz@gmail.com
  skip_cleanup: true
  script: yarn deploy-storybook
  api_key:
    secure: "w0KyKJARUWqrWaFPto/laD1smb3vEvR0xh6RHKuHiuDfcLlPlo19nql71pi3/OHkoFI6lhnS1g/ObFwl95Cw2aMfFf/XT6aduCQUoKxOZoannaRrPtQo/wL1q4RwEIyWxfTYhCXqj50No7e+4t9dO+p/Cvj9zFjqHK1fJjw6HhHUyklDXVTbozrhC7pF3dQ7y4Tb+ZGmbK/ONsoadmXAg2NrGBd7N3JCxq5awNLTCqq/QDBwZm5Y5uOdimttdSXkDAXCL6nMeGu87UC+gcrMDaXeEK4dRL/9H2w4mT6XGOrvyOjI9MVkGLOW4QgEHtFe3pnX560uuSQ8LAFbugqmtkDIcsR+odJwdeEMdkrpnOfLmGnsID9KCcUCB9Kg7MKlZp1DJOfYNWmUdMAGoDsnYHZ9W4iHUIe+r4RVBQgtikcQOr0/Hyo3QpbhtnbpHpmLVTzAVxNg25r0WUUTQIAXsWLnDXkmi3fR6alkh33Qn+dfg7U2hdZLMJ283p0E2EKa4+Ytl1lXKhihq4ORQ7S7uOrVK8U9xtLsEHODA4QYYiCFJxA4kcpOansDRSB0A6XCqKu2zsk4reycgyZtMbnBY6FwF7sW98juXlzkktL+G1h+peJ4OP1us9KDYALtgM0iusblmDK+eU4VfRNccA7daq0rtRlkmgI0W96QE5brY50="
  on:
    tags: true
    repo: 8base/boost
    branch: master
