language: node_js
node_js: node

install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.6.0
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn install

script:
  - yarn run eslint
  - yarn run test
  - yarn run flow

deploy:
  provider: npm
  email: zouxuoz@gmail.com
  skip_cleanup: true
  api_key:
    secure: "PaDpWKzz7qjbK51cyh6bshRexyPAGEIqQJKpk/Q9CiWjw8qQWtn5VxtlAICpI8cgc/O2U28vRcTYtuBQkmKK7COFW/zbmRQVxwvwUVFzP8OYCvv+5rt7dvRgu1byKpnMYx+9J/3tIDtxrDPD5twvM+LaOw2caJ5Qp2Os3iTzsmJ/9fKvcmWJMvNY+MaG63sW030Ve2JkL3K0eb9g27OpxkGeW6HawiBpikAMC8mZzp+DOD0yBm2b8ug2K3nv6UliX6Ze0TCqYGh5YOed61IWANqXGurbLOMaWN8PtdZnIfOyUZ20n2uBePYrt0izQeU+NIi6EALercFYOmKN+eIx7GzIw2MYsZRhzjFl0RmX9jq2u0SCbfJrl5w348q+KWWN59y/HjUbcHH1XGVHJRgu7QDrRGZcBrMjQ5GO4bPwI0XvVMi5OKnsD8/60hpbiggy+3FA670l5gepTuj/wNJEMbhHnAVLp1GwjFSi0StbvkvZLmb1uxlhHc6UUG9IUrt3uA65gvWrGD6R4tfeai15z7yEZhRc0kgMPYsWy66AtSf7AZsHoo2FpWj4rcLTIqXvOoHX1o7qrzrnrRfFW8k2mI9eAs/hE5xWUmwMozySURjNcmoKnEL4LZPU2OsuflrzkD7znebo6DARsNQPKcap2Ei7lZvPMpBdbPJSXqoP1rk="
  on:
    tags: true
    repo: 8base/boost
    branch: master
