language: node_js
node_js: node

env:
  - NODE_PATH=src/

install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.6.0
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn install

script:
  - yarn eslint
  - yarn test --coverage --verbose
  - yarn flow
  - yarn build

deploy:
  provider: npm
  email: zouxuoz@gmail.com
  skip_cleanup: true
  script: yarn deploy-storybook
  api_key:
    secure: XMco38FVN4j9BA/fSBgXnpcm8E92LnRp4Yn83Uh8UBHyEMipAj48vNcBWHSyUmZGbq22197Hj0k9w2qeKCjmw5rnJ0LQHgStQIH82nsFdAS2uf4Ff1wWPiPGXpveSNAo5oytIwc9mjH/VtqdmR9f+h0SSV0epqB//clrtMdjKYTrpgLlYMfMDrqPCT1Rw/c+0WgwT+2iCFg6FHgEgM1oKeRqRX6hiy6EkMqDGc2/UnYDDn48Xd6wCl1Zq4oGmNmpuK23vzk3KJNzZ06k4GtLn+Wkw3/dB0aWGdgW2ibbSeEQrmcUvjxWfk84asolOhOfj3kpFr3mIFEZ0BYFgnZ0F37Z0UOX3vJZG1YTgnLHatVFdotryMPG+VKXlFWDzzSxKycYbYawuYjTpA3GJjE8eNjTGcZtRPDIKjyn8DOfdnI027aVGr6AZYcNlu0qu2j08WuKTWuZ94IwDrJJQYMhBefn2IqUg6ESdG4bl80nFhSXjFMfXPD/2QwbeUi1A8n4jDFZ3s45cqZiUZPvqQBE14SxtvMZYdmCb0sfWza5S67PEgEa1pwebB870MwXQhUnrb6lmWArvayjPypH/gS4VEt0OgiRPs6vaumb/bw2p+XvuxzleAvlWoXYsJxYRdSzEgncGlYklSXsDK+Xq/PDLqWop8jQUpfu6VyHiAYko9Q=
  on:
    tags: true
    repo: 8base/boost
    branch: master
