// @flow
import * as DSM from './dsmColors';

const DEFINE_PALETTE = {
  WHITE: '#FFFFFF',
  BLACK: DSM.GREY_COLORS.DSM_BLACK,

  DARK_GRAY1: '#323c47',
  DARK_GRAY2: '#3E4650',
  DARK_GRAY3: '#444D57',

  GRAY1: '#878c93',
  GRAY2: '#5C6268',
  GRAY3: '#737A82',
  GRAY4: '#7e868e',
  GRAY5: '#A5AFB6',

  LIGHT_GRAY1: '#d0d7dd',
  LIGHT_GRAY2: '#DCE1E6',
  LIGHT_GRAY3: '#E5E9EC',
  LIGHT_GRAY4: '#EDF0F2',
  LIGHT_GRAY5: '#f4f7f9',

  YELLOW: '#ffd012',
  PURPLE: '#9975D0',
  PINK: '#EB518E',

  LIGHT_BLUE: '#4DA1FF',
  BLUE: '#1968cb',
  DARK_BLUE: '#687695',

  LIGHT_GREEN: '#a6e50f',
  GREEN: '#00bb6e',

  LIGHT_RED: '#ff6d4a',
  RED: '#eb4235',

  TRANSPARENT: 'transparent',

  DSM,

  // TODO: delete after colors collisions resolve
  ...DSM.MAIN_BRAND_COLORS,
  ...DSM.GREY_COLORS,
  ...DSM.NAVIGATION_COLORS,
  ...DSM.SECONDARY_COLORS,
};

const PALETTE = {
  ...DEFINE_PALETTE,

  PRIMARY: DEFINE_PALETTE.LIGHT_BLUE,
  SECONDARY: DEFINE_PALETTE.GREEN,
  SUCCESS: DEFINE_PALETTE.LIGHT_GREEN,
  DANGER: DEFINE_PALETTE.LIGHT_RED,
  DANGER_DARK: DEFINE_PALETTE.RED,
  TRANSPARENT: DEFINE_PALETTE.TRANSPARENT,
};

const COLORS = {
  ...PALETTE,

  PRIMARY_BORDER_COLOR: PALETTE.LIGHT_GRAY1,
  PRIMARY_HOVER_GRAY_COLOR: DSM.GREY_COLORS.DSM_LIGHT_GREY_3,
  DISABLED_COLOR: PALETTE.LIGHT_GRAY1,
  PLACEHOLDER_COLOR: PALETTE.LIGHT_GRAY1,

  DISABLED_TEXT_COLOR: PALETTE.LIGHT_GRAY1,
  PRIMARY_TEXT_COLOR: PALETTE.DARK_GRAY1,
  SECONDARY_TEXT_COLOR: PALETTE.GRAY1,

  LIGHT_DISABLED_TEXT_COLOR: 'rgba(255, 255, 255, 0.38)',
  LIGHT_PRIMARY_TEXT_COLOR: 'rgba(255, 255, 255, 1)',
  LIGHT_SECONDARY_TEXT_COLOR: 'rgba(255, 255, 255, 0.87)',
};

export { COLORS, PALETTE };
